### ISSUE TITLE
Can you adjust the example by adding the client side build too, and hydration?

### ISSUE THREAD

**Issue by valentinvieriu** [tbgse/vite-ssr-example#1]
Hi Tobias, I've watched closely https://github.com/vitejs/vite/issues/711, and tried to replicate that setup, but somehow I'm missing some steps. The example here is not even close to the findings in the above mentioned issue. 

Is it possible to adapt this example to showcase a full SSR ( with client side hydration) example with Vite?

This would be much appreciated, as this is not mentioned anywhere at this moment.

Thank you

**Comment by tbgse** [comment]
hi @valentinvieriu it turns out there are still a few more moving parts that seem to be work in progress in vite as well as rollup to make SSR happen correctly. Those pieces are slowly coming together. See this issue here: vitejs/vite#764 and at rollup here rollup/rollup#3760 and rollup/rollup#3764

There is a workaround mentioned in the vite issue as well that I tried out and it seemed to work well enough. Expanding this example is a good idea, I'll try to find time to do this in the next days.

**Comment by valentinvieriu** [comment]
Thank you for the quick reply. 
I have some question that maybe you can help if you have the time:
- Where should this custom build section go? in `vite.config.js`. It seems I'm not the only one confused here (https://github.com/vitejs/vite/issues/278)
- Do we need to replace the `/src/main.js` from the index.html to `<script type="module" src="/src/entry-client.js"></script>`?. 

If I do the steps above, I get the server build only on `vite` but on `vite build` i only get the client build.

I must say I've got lost at lower level than the one you probably are. I'm still trying to get the real basic going

I will continue to monitor this repo then, for your updates.

Thank you again for your clarifications

**Comment by tbgse** [comment]
I just updated the example, your questions should be answered by looking at the code. 

The custom build section is its own file that we will run as npm script with `npm run build` instead of vite build (see package.json in the code). Just like you said, you'd need to replace the reference to the js file in the `index.html`.

This is all still more of a proof of concept than anything that could actually be used in production. Let me know how far you can get from here and if you end up running into issues.

**Comment by valentinvieriu** [comment]
@tbgse thank you very much for your quick response. Now that I look backwards, it makes sense, but when I was in the middle of the challenge, I kept thinking that this custom build, needs to be somehow part of vite ecosystem.
Thank you for clarifying this and modifying the code. This is already a good start
I'm actually trying to adapt this build process, to work with Cloudflare Workers, so I'll have to adapt the SSR Build code to work in a webworker like env that exists inside a Cloudflare Worker
Feel free to join/ check https://vueflare.com/
Thank you again for your fast response

**Comment by tbgse** [comment]
That's funny because I am working on exactly the same thing, inspired by
react flare as well. That was the main reason I was looking into all this.

**Comment by valentinvieriu** [comment]
This is funny indeed. Please join me then on building [VueFlare](https://vueflare.com/). I've just created the [organization](https://github.com/orgs/vueflare/) yesterday and bought the domain name. I was also inspired by React Flare.
I've actually build couple of projects in the past based on @l5x [vue-ssr-cloudflare-workers-template](https://github.com/l5x/vue-ssr-cloudflare-workers-template) and really see some interesting potential here with Cloudflare Workers

**Comment by tbgse** [comment]
happy to join forces on this @valentinvieriu maybe let's set up a discord / chat to have a more detailed discussion around the objectives etc.

**Comment by frandiox** [comment]
@valentinvieriu @tbgse Hi! I've been following SSR related issues to make this work in CF Workers for a while as well 😅 
Do you mind if I join you?
